"""Add settings for puns cooldown

Revision ID: 614bb9e370d8
Revises: 381d2407fcf3
Create Date: 2023-05-29 20:55:26.456843

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = "614bb9e370d8"
down_revision = "381d2407fcf3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "puns_cooldown", sa.BigInteger(), nullable=False, server_default="60"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # check if column exists before adding
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    columns = [col["name"] for col in inspector.get_columns("puns")]
    if "last_invoked" not in columns:
        op.add_column("puns", sa.Column("last_invoked", sa.DateTime(), nullable=True))

    result = bind.execute(
        sa.text('SELECT id FROM bot_settings WHERE id = 1')
    ).fetchone()

    if not result:
        op.execute('INSERT INTO bot_settings (id) VALUES (1)')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("puns", "last_invoked")
    op.drop_table("bot_settings")
    # ### end Alembic commands ###
