[phases.setup]
aptPkgs = ["python3", "python3-pip", "python-is-python3", "libpq-dev", "python3-dev", "postgresql"]   # Install the wget package with apt-get

[phases.build]
cmds = ["pip install psycopg2-binary nltk", "pip install ."]

[start]
cmd = "grace start"