[phases.setup]
aptPkgs = ["python3", "python-is-python3", "python-pip3", "libpq-dev", "python3-dev", "postgresql"]   # Install the wget package with apt-get

[phases.build]
cmds = ["pip3 install psycopg2-binary nltk", "pip3 install ."]

[start]
cmd = "python -m alembic upgrade head && python -m grace db seed && python -m grace start"
