[phases.setup]
aptPkgs = ["python", "python-pip", "libpq-dev", "python3-dev", "postgresql"]   # Install the wget package with apt-get

[phases.build]
cmds = ["pip install psycopg2-binary nltk", "pip install ."]

[start]
cmd = "python -m alembic upgrade head && python -m grace db seed && python -m grace start"
