[phases.setup]
aptPkgs = ["python3", "python3-pip", "python-is-python3", "libpq-dev", "python3-dev"]   # Install the wget package with apt-get

[phases.build]
cmds = ["sh bin/server_build.sh", "pip install psycopg2-binary", "pip install ."]

[start]
cmd = "grace start"