[phases.setup]
aptPkgs = ["python3", "python3-pip", "python-is-python3", "python3.10-venv", "libpq-dev", "python3-dev", "postgresql"]   # Install the wget package with apt-get

[phases.build]
cmds = ["pip3 install psycopg2-binary nltk", "pip3 install ."]

[start]
cmd = "python3 -m alembic upgrade head && python3 -m grace db seed && python3 -m grace start"
