[phases.setup]
aptPkgs = ["python3", "python3-pip", "python-is-python3", "libpq-dev", "python3-dev", "postgresql"]   # Install the wget package with apt-get

[phases.build]
cmds = ["python3 -m venv venv", "source venv/bin/activate ", "pip3 install psycopg2-binary nltk", "pip3 install ."]

[start]
cmd = "alembic upgrade head && grace db seed && grace start"
