# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Grace tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Lint with ruff
      run: |
        ruff check --preview

    - name: Generate config file
      run: |
        mkdir -p config
        cat <<EOF > config/database.cfg
        [database.production]
        url = ${DATABASE_URL}

        [database.development]
        adapter = sqlite
        database = grace_development.db

        [database.test]
        adapter = sqlite
        database = grace_test.db
        EOF
        
    - name: Test with pytest
      run: |
        pytest -v
